# app/_config/routes.yml
---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'home': 'AnnaHjerpyn\Custom\Controllers\WordBankController'
    'user': 'AnnaHjerpyn\Custom\Controllers\UserAccountController'

