---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'word-bank': 'AnnaHjerpyn\Custom\Controllers\WordBankController'
    'word-bank/$Action': 'AnnaHjerpyn\Custom\Controllers\WordBankController'
    'word-bank//$Action/$ID': 'AnnaHjerpyn\Custom\Controllers\WordBankController'
