# app/_config/routes.yml
---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'home': 'AnnaHjerpyn\Custom\Controllers\WordBankController'
    'login': 'AnnaHjerpyn\Custom\Controllers\CustomLoginController'
    'statistic': 'AnnaHjerpyn\Custom\Controllers\UserStatisticsController'


