<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;

    class Page extends SiteTree
    {
        public function getCMSFields()
        {
            $fields = parent::getCMSFields();

            $fields->removeByName(['H1']);

            $fields->addFieldsToTab('Root.Main', []);

            return $fields ; // TODO: Change the autogenerated stub
        }
    }
}
