<?php

namespace AnnaHjerpyn\Custom\PageTypes\Controllers;

use PageController;
use SilverStripe\View\Requirements;

class ComponentPageController extends PageController
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        Requirements::themedJavascript('nav');
    }
}
