<?php

namespace AnnaHjerpyn\Custom\PageTypes\Controllers;

use PageController;

class HomePageController extends PageController
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
